name: Kwiki-Comments
version: 0.01
abstract: Post Comments to Kwiki Pages
author: Kang-min Liu (gugod@gugod.org)
license: perl
distribution_type: module
requires:
  Kwiki: 0
  DBD::SQLite: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
